return {
    descriptions = {},
    misc = {
        dictionary = {
            teo_reload = "手动重载",
            teo_adapted_mods = "适配的模组",
            teo_adapted_mods2 = "已适配的模组",
            teo_adapted_mods3 = "人工翻译的模组列表",
            b_t_by = "译者：",
            teo_show_original = "显示原版翻译",
            teo_show_original_blind = "显示盲注原版翻译",
            teo_original_tooltip = "原版翻译",
            teo_actions = "操作",
            teo_optional_config = "可选配置",
            teo_runtime_override = "在内存中动态翻译",
            teo_enable_ai = "启动AI翻译",
            teo_set_api_key = "设置API Key",
            teo_api_key_popup_title = "请输入翻译的 API Key",
            teo_b_set = "确认",
            teo_b_cancel = "取消",
            teo_b_clear = "清空内容",
            teo_b_get_key = "获取 API Key",
        },
    },
}
